# Site settings
title: Ed's Blog
header-img: img/home-bg.jpg
email: ed@edparsons.co.uk
description: "The thoughts of a serial thinker"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://edparsons.github.io"
twitter_username: edparso
github_username:  edparsons
facebook_username:  mr.ed.parsons

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
